### ISSUE TITLE
API Token in Source Code

### ISSUE THREAD

**Issue by crookedneighbor** [DrStrangepork/habitica-scripts#3]
You've checked in your API token into your script. This will allow anyone to make changes to your account without your permission. We're going to reset the token so you will need to log out and log back into to the site/mobile apps and input your new api token into any integration that uses it. 

https://github.com/DrStrangepork/habitica-scripts/blob/09ba33dc9e9a337972bc319b1d24e83bd57aa200/cast-party-spells.py#L14-L15

**Comment by DrStrangepork** [comment]
damn it, I did that again!?

**Comment by DrStrangepork** [comment]
Hold-over from an old template. I have removed all references to IDs and tokens from all scripts.
