### ISSUE TITLE
No script is working for me

### ISSUE THREAD

**Issue by therealmaxmoon** [DrStrangepork/habitica-scripts#4]
I use zsh but python and jq is installed. Do I miss something?

`./push-todos-with-duedates-to-top.py `
Traceback (most recent call last):
  File "./push-todos-with-duedates-to-top.py", line 11, in <module>
    today = unicode(time.strftime("%Y-%m-%d"))
NameError: name 'unicode' is not defined

`./am-i-sleeping.py     `                                                                                                         1 ↵
  File "./am-i-sleeping.py", line 37
    print "Yes"
              ^
SyntaxError: Missing parentheses in call to 'print'

`./party-health-check.sh `
jq: error (at <stdin>:0): null (null) has no keys

**Comment by DrStrangepork** [comment]
Try all these again using python 2.7

**Comment by DrStrangepork** [comment]
Is this still an issue for you?
