### ISSUE TITLE
can't configure my user id and api token

### ISSUE THREAD

**Issue by Amrjit55** [DrStrangepork/habitica-scripts#8]
i complete ur installation of  habitica push to do due date to top, I complete in git clone reposition and pip install -r requirement txt. But when I trying to configure my user id and API token, your command line –
USR = os.getenv('HAB_API_USER', "YOUR_USERID_HERE")
   KEY = os.getenv('HAB_API_TOKEN', "YOUR_KEY_HERE")
 
I entered this command line but it shows this -
 
![image](https://user-images.githubusercontent.com/89153574/133806496-5f9c08b3-9216-4d7b-ba9e-aac09a79a652.png)

As same as key also
 
Kindly, would you help me please this issue of configuration.

**Comment by DrStrangepork** [comment]
That is the Python to read those variables from the system, not the commands to set those values. For Windows, you'd need to set user environment variables: Control Panel, User Accounts, Change my environment variables. Then create variables HAB_API_USER and HAB_API_TOKEN with their appropriate values. Then open a new CMD window and try running the Python scripts again.

**Comment by Amrjit55** [comment]
![Screenshot 2021-09-18 134402](https://user-images.githubusercontent.com/89153574/133881921-b326a88d-62b3-4cb6-83d4-4e47c1250765.png)

I create environment variable HAB_API_USER and HAB_API_TOKEN with values as my habitica user id and api token.
But what python script use to run again. What script i write to run again? please tell me this.
 I again run git clone reposition and pip -r requirement txt. Then what do I next, please tell me.

**Comment by Amrjit55** [comment]
Check my comment on Ur reposition issues.
 I create env. Variable of HAB_API_ USER and HAB_API_TOKEN with values as
of user id and api token respectively.
 But I don't know what to do next still not change. I run cmd and install
git clone reposition, and pip -r requirment txt also. Still not working.
 So, please help me.

**Comment by DrStrangepork** [comment]
In your CMD shell, you can run the `set` command to confirm that your environment variables `HAB_API_USER` and `HAB_API_TOKEN` are set. If you see that - and you should based on the image you uploaded earlier - then all Python commands should run normally. 

I believe you are trying to run the `push-todos-with-duedates-to-top.py` command. You can run that script by typing `push-todos-with-duedates-to-top.py` and hitting Return/Enter. If you do not see any result from that command, then it should have worked properly, and you should see any of your to-dos that have a due date at the top of your To Do list in Habitica. If you do not have any to-dos configured with a due date, then you will see no change to your to-dos.

**Comment by Amrjit55** [comment]
I am very thankful for your help.

 I enter set command and It shows above environment variables, So it is true.
But when i enter this push-todos-with-duedates-to-top.py command it shows nothing but this-
![Screenshot 2021-09-20 084937](https://user-images.githubusercontent.com/89153574/133954064-e770f693-8977-4c88-9969-2ac0ef950ccb.png)
Is this ok.

**Comment by Amrjit55** [comment]
Thanks for your help, It all set, I show due with sorted from a month to top and  today below and further future date also.
now, i am so glad. Thankyou for your help.

**Comment by DrStrangepork** [comment]
Glad it's working for you. Closing ticket.
